/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BarChartOutlined: typeof import('@ant-design/icons-vue')['BarChartOutlined']
    ChatBubble: typeof import('./../src/components/ChatBubble.vue')['default']
    CommentOutlined: typeof import('@ant-design/icons-vue')['CommentOutlined']
    DeleteOutlined: typeof import('@ant-design/icons-vue')['DeleteOutlined']
    EyeOutlined: typeof import('@ant-design/icons-vue')['EyeOutlined']
    LeftSidebar: typeof import('./../src/components/LeftSidebar.vue')['default']
    LineChartOutlined: typeof import('@ant-design/icons-vue')['LineChartOutlined']
    MdPreview: typeof import('./../src/components/MdPreview.vue')['default']
    PieChartOutlined: typeof import('@ant-design/icons-vue')['PieChartOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondLeftSidebar: typeof import('./../src/components/SecondLeftSidebar.vue')['default']
    SenderInput: typeof import('./../src/components/SenderInput.vue')['default']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    TableOutlined: typeof import('@ant-design/icons-vue')['TableOutlined']
    WelcomeIndex: typeof import('./../src/components/WelcomeIndex.vue')['default']
  }
}
